on: push
name: Deploy website on push
jobs:
  web-deploy:
    name: FTP-Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Get latest code
        uses: actions/checkout@v3

      - name: Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.3.3
        with:
          server: 206.189.45.148
          username: agsofts
          password: ${{ secrets.ftp_password }}
          server-dir: nyla_dev/web/test/
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%dT%H:%M:%S')"
      - uses: snow-actions/line-notify@v1.1.0
        with:
          access_token: ${{ secrets.LINE_ACCESS_TOKEN }}
          message: Deploy test system >> ${{ date }}
